/**
 * Core domain entity for a Note.
 *
 * This is the single source of truth for what a Note *is*.
 * Keep it pure — no framework imports, no persistence concerns.
 */
export interface Note {
  id: string;
  title: string;
  body: string;
  tags: string[];
  isArchived: boolean;
  createdAt: string;
  updatedAt: string;
}

/**
 * Shape required to create a new note.
 * `id` and timestamps are generated by the repository.
 */
export interface CreateNoteInput {
  title: string;
  body: string;
  tags?: string[];
}

/**
 * Shape required to update an existing note.
 * All fields are optional — only provided fields change.
 */
export interface UpdateNoteInput {
  title?: string;
  body?: string;
  tags?: string[];
}
